name: bijou_cafe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.0
  cloud_firestore: ^4.8.5
  permission_handler: ^10.4.3
  intl: ^0.18.1
  transparent_image: ^2.0.1
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
